//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Master {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Master.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 using H.Core.DataAccess;
        ///using H.Core.Utility;
        ///using H.Entity;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Data;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace H.Service.SqlDataAccess
        ///{
        ///    /// &lt;summary&gt;
        ///    /// $$$Remark$$$DA
        ///    /// &lt;/summary&gt;
        ///    public class $$$TableName$$$DataAccess
        ///    {
        ///    
        ///        public List&lt;$$$TableName$$$Entity&gt; Search(QueryCondition&lt;$$$TableName$$$Entity&gt; entity)
        ///        {
        ///            CustomDataCommand command = DataCommandManager.CreateCus [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DataAccess_Assembly {
            get {
                return ResourceManager.GetString("DataAccess_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using H.Core.DataAccess;
        ///using H.Core.Utility;
        ///using H.Entity;
        ///using H.Service.IDataAccess;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Data;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace H.Service.SqlDataAccess
        ///{
        ///    /// &lt;summary&gt;
        ///    /// $$$Remark$$$DA
        ///    /// &lt;/summary&gt;
        ///    [VersionExport(typeof(I$$$TableName$$$DataAccess))]
        ///    public class $$$TableName$$$DataAccess : I$$$TableName$$$DataAccess
        ///    {
        ///    
        ///        public List&lt;$$$TableName$$$Entity&gt; Search(QueryCondi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DataAccesstxt {
            get {
                return ResourceManager.GetString("DataAccesstxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;  
        ///&lt;dataOperations xmlns=&quot;http://zhy.seo.sh.cn/DataOperation&quot;&gt;
        ///  &lt;dataCommand name=&quot;$$$TableName$$$Search&quot; database=&quot;CenterDataBase&quot; commandType=&quot;Text&quot;&gt;
        ///    &lt;commandText&gt;
        ///      &lt;![CDATA[
        ///		SELECT @TotalCount = COUNT(2) FROM [dbo].[$$$TableName$$$] #StrWhere#
        ///			
        ///		SELECT *,@TotalCount AS TotalCount FROM (
        ///			SELECT TOP (@EndNumber) *,(ROW_NUMBER() OVER(ORDER BY  sm.sysno DESC )) AS RowNumber
        ///			FROM [dbo].[$$$TableName$$$] sm WITH (NOLOCK)
        ///			#StrWhere#
        ///		)s [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DbCommandxml {
            get {
                return ResourceManager.GetString("DbCommandxml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Runtime.Serialization;
        ///using System.Text;
        ///
        ///namespace H.Entity
        ///{
        ///  //$$$Remark$$$
        ///  [DataContract(Namespace = &quot;http://zhy.seo.sh.cn&quot;)]
        ///  [Serializable]
        ///  public class $$$TableName$$$Entity : PageBase
        ///  {
        ///  
        ///    $$$DefaultStructure$$$
        ///    $$%FildBegin%$$
        ///	/// &lt;summary&gt;
        ///	/// $$$FileRemark$$$
        ///	/// &lt;/summary&gt;
        ///	[DataMember]
        ///	public $$$FileType$$$ $$$FileName$$$
        ///	{
        ///		get; set;
        ///	}
        ///    $$%FildEnd%$$
        ///    
        ///    [Da [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Entitytxt {
            get {
                return ResourceManager.GetString("Entitytxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using H.Core.Utility;
        ///using H.Entity;
        ///using H.Service.SqlDataAccess;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace H.Website.Facade
        ///{
        ///	/// &lt;summary&gt;
        ///    /// $$$Remark$$$Facade
        ///    /// &lt;/summary&gt;
        ///    public class $$$TableName$$$Facade
        ///    {
        ///
        ///        static $$$TableName$$$DataAccess access = new $$$TableName$$$DataAccess();
        ///        /// &lt;summary&gt;
        ///        /// 
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;log&quot;&gt;&lt;/param&gt;
        ///        public stat [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Facade_Assembly {
            get {
                return ResourceManager.GetString("Facade_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using H.Core.Utility;
        ///using H.Entity;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace H.Website.Facade
        ///{
        ///	/// &lt;summary&gt;
        ///    /// $$$Remark$$$Facade
        ///    /// &lt;/summary&gt;
        ///    public class $$$TableName$$$Facade
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// 
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;log&quot;&gt;&lt;/param&gt;
        ///        public static List&lt;$$$TableName$$$Entity&gt; Search(QueryCondition&lt;$$$TableName$$$Entity&gt; entity)
        ///        {
        ///            return Res [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Facadetxt {
            get {
                return ResourceManager.GetString("Facadetxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using H.Entity;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace H.Service.IDataAccess
        ///{
        ///    /// &lt;summary&gt;
        ///    /// $$$Remark$$$Interface
        ///    /// &lt;/summary&gt;
        ///    public interface I$$$TableName$$$DataAccess
        ///    {
        ///
        ///        List&lt;$$$TableName$$$Entity&gt; Search(QueryCondition&lt;$$$TableName$$$Entity&gt; entity);
        ///
        ///        int Insert$$$TableName$$$($$$TableName$$$Entity entity);
        ///
        ///        int Update$$$TableName$$$($$$TableName$$$Entity entity);
        ///
        ///        in [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IDataAccesstxt {
            get {
                return ResourceManager.GetString("IDataAccesstxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;%@ Page Title=&quot;&quot; Language=&quot;C#&quot; MasterPageFile=&quot;~/Master/Maintain.Master&quot; AutoEventWireup=&quot;true&quot; CodeBehind=&quot;Maintain.aspx.cs&quot; Inherits=&quot;H.Website.IISHost.Pages.$$$TableName$$$.Maintain&quot; %&gt;
        ///
        ///&lt;asp:Content ID=&quot;Content1&quot; ContentPlaceHolderID=&quot;cph_Head&quot; runat=&quot;server&quot;&gt;
        ///    &lt;link href=&quot;/WebResource/css/upload/uploadify.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///    &lt;link href=&quot;/WebResource/css/uniform.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///    &lt;link href=&quot;/WebResource/css/select2.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///    &lt;link href=&quot;/WebResource/css/ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Maintainaspx {
            get {
                return ResourceManager.GetString("Maintainaspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Web;
        ///using System.Web.UI;
        ///using System.Web.UI.WebControls;
        ///using H.Website.Facade;
        ///using H.Entity;
        ///
        ///namespace H.Website.IISHost.Pages.$$$TableName$$$
        ///{
        ///    [AjaxPro.AjaxNamespace(&quot;Portal.Maintain&quot;)]
        ///    public partial class Maintain : H.Website.Facade.PageBase
        ///    {
        ///        public string UploadUrl
        ///        {
        ///            get;
        ///            set;
        ///        }
        ///
        ///        public string UploadImageUrl
        ///        {
        ///          [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Maintainaspxcs {
            get {
                return ResourceManager.GetString("Maintainaspxcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //------------------------------------------------------------------------------
        ///// &lt;自动生成&gt;
        /////     此代码由工具生成。
        /////
        /////     对此文件的更改可能会导致不正确的行为，并且如果
        /////     重新生成代码，这些更改将会丢失。 
        ///// &lt;/自动生成&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace H.Website.IISHost.Pages.$$$TableName$$$ {
        ///    
        ///    
        ///    public partial class Maintain {
        ///        
        ///        /// &lt;summary&gt;
        ///        /// Form1 控件。
        ///        /// &lt;/summary&gt;
        ///        /// &lt;remarks&gt;
        ///        /// 自动生成的字段。
        ///        /// 若要进行 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Maintainaspxdesignercs {
            get {
                return ResourceManager.GetString("Maintainaspxdesignercs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.ServiceModel;
        ///using System.ServiceModel.Activation;
        ///using System.ServiceModel.Web;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using H.Core.Utility;
        ///using H.Entity;
        ///using H.Core.Utility.Log;
        ///using H.Service.IDataAccess;
        ///
        ///namespace H.Service.Rest
        ///{
        ///    /// &lt;summary&gt;
        ///    /// $$$Remark$$$Interface
        ///    /// &lt;/summary&gt;
        ///    [ServiceContract]
        ///    [AspNetCompatibilityRequirements(RequirementsMode = AspNetCompatibi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string RestServicetxt {
            get {
                return ResourceManager.GetString("RestServicetxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;%@ Page Title=&quot;&quot; Language=&quot;C#&quot; MasterPageFile=&quot;~/Master/Master.Master&quot; AutoEventWireup=&quot;true&quot; CodeBehind=&quot;$$$TableName$$$.aspx.cs&quot; Inherits=&quot;H.Website.IISHost.Pages.$$$TableName$$$.$$$TableName$$$&quot; %&gt;
        ///
        ///&lt;asp:Content ID=&quot;Content1&quot; ContentPlaceHolderID=&quot;cph_Head&quot; runat=&quot;server&quot;&gt;
        ///
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/WebResource/css/datepicker.css&quot; /&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; href=&quot;/WebResource/css/select2.css&quot; /&gt;
        ///    &lt;link href=&quot;../../WebResource/css/uniform.css&quot; rel=&quot;stylesheet&quot; /&gt;
        ///    &lt;link href=&quot;http [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WebPageaspx {
            get {
                return ResourceManager.GetString("WebPageaspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Web;
        ///using System.Web.UI;
        ///using System.Web.UI.WebControls;
        ///using H.Website.Facade;
        ///using H.Entity;
        ///using H.Website.Facade.Facade;
        ///using H.Core.Utility;
        ///
        ///
        ///namespace H.Website.IISHost.Pages.$$$TableName$$$
        ///{
        ///    [AjaxPro.AjaxNamespace(&quot;Portal.$$$TableName$$$&quot;)]
        ///    public partial class $$$TableName$$$ : H.Website.Facade.PageBase
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// 不需登录验证
        ///        /// &lt;/summary&gt;
        ///        prote [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WebPageaspxcs {
            get {
                return ResourceManager.GetString("WebPageaspxcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //------------------------------------------------------------------------------
        ///// &lt;自动生成&gt;
        /////     此代码由工具生成。
        /////
        /////     对此文件的更改可能会导致不正确的行为，并且如果
        /////     重新生成代码，这些更改将会丢失。 
        ///// &lt;/自动生成&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace H.Website.IISHost.Pages.$$$TableName$$$ {
        ///    
        ///    
        ///    public partial class $$$TableName$$$ {
        ///        
        ///        /// &lt;summary&gt;
        ///        /// Form1 控件。
        ///        /// &lt;/summary&gt;
        ///        /// &lt;remarks&gt;
        ///        /// 自动生成的字段。
        ///        / [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WebPageaspxdesignercs {
            get {
                return ResourceManager.GetString("WebPageaspxdesignercs", resourceCulture);
            }
        }
    }
}
